name: deploy

on:
  push:
    branches: [ deploy ]

env:
  AZURE_WEBAPP_NAME: signinwithapple
  AZURE_WEBAPP_PACKAGE_PATH: './artifacts/signinwithapple'
  DOTNET_VERSION: '3.1.201'

jobs:
  deploy:
    name: ${{ env.AZURE_WEBAPP_NAME }}
    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build and Publish
      shell: pwsh
      run: ./build.ps1 -OutputPath '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        NUGET_XMLDOC_MODE: skip

    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
