name: update-dotnet-sdk

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    name: Update .NET SDK
    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update .NET SDK
      shell: pwsh
      run: ./update-dotnet-sdk.ps1 -Channel "3.1" -GitHubToken ${{ secrets.ACCESS_TOKEN }} -UserName "martincostello" -UserEmail "martin@martincostello.com"
      if: ${{ github.repository_owner == 'martincostello' }}
