name: update-static-assets

on:
  schedule:
    - cron:  '0 5 * * *'
  workflow_dispatch:

jobs:
  update-static-assets:
    name: Update static assets
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork == false }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update static assets
      uses: martincostello/update-static-assets@v1
      with:
        labels: dependencies
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        user-email: 102549341+costellobot@users.noreply.github.com
        user-name: costellobot
